# Generated by Django 3.1.1 on 2023-07-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='place',
            field=models.CharField(default='chennai', max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='referencenumber',
            field=models.CharField(help_text='reference number', max_length=20, primary_key=True, serialize=False),
        ),
    ]
